docking_params:
  dock_timeout_s: 900
  energy_range: 3.0
  exhaustiveness: 20
  min_rmsd: 1.0
  n_cpu: null
  num_conformers: 20
  num_modes: 9
ligands:
  BENZ_R: CC(=O)N[C@H](C1=CC=CC=C1)C2=C([O-])C3=CC=CC=C3OC2=O
  BENZ_S: CC(=O)N[C@@H](C1=CC=CC=C1)C2=C([O-])C3=CC=CC=C3OC2=O
  R_Warfarin_ref: CC(=O)C[C@H](C1=CC=CC=C1)C2=C([O-])C3=CC=CC=C3OC2=O
  S_Warfarin_ref: CC(=O)C[C@@H](C1=CC=CC=C1)C2=C([O-])C3=CC=CC=C3OC2=O
  dimethoxy_23_R: CC(=O)N[C@H](c1c(OC)c(OC)ccc1)C2=C([O-])C3=CC=CC=C3OC2=O
  dimethoxy_23_S: CC(=O)N[C@@H](c1c(OC)c(OC)ccc1)C2=C([O-])C3=CC=CC=C3OC2=O
  m_bromo_R: CC(=O)N[C@H](C1=CC(=CC=C1)Br)C2=C([O-])C3=CC=CC=C3OC2=O
  m_bromo_S: CC(=O)N[C@@H](C1=CC(=CC=C1)Br)C2=C([O-])C3=CC=CC=C3OC2=O
  m_nitro_R: CC(=O)N[C@H](C1=CC(=CC=C1)[N+](=O)[O-])C2=C([O-])C3=CC=CC=C3OC2=O
  m_nitro_S: CC(=O)N[C@@H](C1=CC(=CC=C1)[N+](=O)[O-])C2=C([O-])C3=CC=CC=C3OC2=O
  p_nitro_R: CC(=O)N[C@H](C1=CC=C([N+](=O)[O-])C=C1)C2=C([O-])C3=CC=CC=C3OC2=O
  p_nitro_S: CC(=O)N[C@@H](C1=CC=C([N+](=O)[O-])C=C1)C2=C([O-])C3=CC=CC=C3OC2=O
project_name: Coumarin_Derivatives_Anticoagulant_Study
receptors:
  VKORC1_Human:
    chain: A
    flexible_residues:
    - A:217
    - A:276
    - A:269
    - A:272
    native_ligand_resname: SWF
    padding: 6.0
    pdb_id: 6WV3
