#!/usr/bin/env python3
"""
generate_chimerax_scenes.py

Standalone Python script to generate UCSF ChimeraX command scripts (.cxc files)
for the top-performing docked ligand poses identified in virtual screening.
"""

import os
import glob
import pandas as pd
from pathlib import Path

def locate_receptor_pdb(receptor_name):
    """
    Dynamically searches for the best matching receptor PDB file on disk.
    Prioritizes protonated structures, then custom, clean, and raw structures.
    """
    search_dirs = [
        "proteins/protonated",
        "proteins/custom",
        "proteins/clean",
        "proteins/raw"
    ]
    
    for s_dir in search_dirs:
        if not os.path.exists(s_dir):
            continue
            
        # 1. Exact match search
        for ext in [".pdb", ".pdbqt"]:
            direct_path = os.path.join(s_dir, f"{receptor_name}{ext}")
            if os.path.exists(direct_path):
                return direct_path
        
        # 2. Pattern-based search to handle chain and protonation suffixes
        pattern = os.path.join(s_dir, f"*{receptor_name}*.pdb")
        matches = glob.glob(pattern)
        if matches:
            # Prefer files with "protonated" in the name if available
            protonated_matches = [m for m in matches if "protonated" in m.lower()]
            if protonated_matches:
                return protonated_matches[0]
            return matches[0]
            
    return None

def locate_docked_ligand(receptor_name, ligand_name):
    """
    Dynamically searches for the docked ligand PDBQT file in the output directories.
    Looks inside results/docked_poses/{receptor}/ and falls back to results/docked_poses/.
    """
    search_paths = [
        os.path.join("results", "docked_poses", receptor_name),
        os.path.join("results", "docked_poses"),
        "results"
    ]
    
    for base_path in search_paths:
        if not os.path.exists(base_path):
            continue
            
        # Search using common naming schemas generated by the pipeline
        patterns = [
            f"*{ligand_name}*_{receptor_name}*_docked.pdbqt",
            f"*{ligand_name}*_out.pdbqt",
            f"*{ligand_name}*.pdbqt",
            f"*{ligand_name}*docked.pdbqt"
        ]
        for pat in patterns:
            matches = glob.glob(os.path.join(base_path, pat))
            if matches:
                return matches[0]
                
    return None

def main():
    # Setup output directory
    output_dir = "scenes"
    os.makedirs(output_dir, exist_ok=True)
    
    results_csv = os.path.join("results", "docking_results.csv")
    
    # Fallback to look for individual screening CSVs if a merged file is missing
    if not os.path.exists(results_csv):
        screening_files = glob.glob("results/docked_poses/*/*_screening_results.csv")
        if screening_files:
            print(f"[INFO] Merged 'docking_results.csv' not found. Re-assembling from screening outputs...")
            dfs = []
            for sf in screening_files:
                target_name = Path(sf).stem.replace("_screening_results", "")
                try:
                    temp_df = pd.read_csv(sf)
                    # Convert standard output format to dynamic table mapping
                    temp_df = temp_df[['ligand_name', 'best_affinity']].rename(
                        columns={'ligand_name': 'Ligand', 'best_affinity': target_name}
                    )
                    dfs.append(temp_df)
                except Exception as e:
                    print(f"  [WARNING] Could not parse file {sf}: {e}")
            if dfs:
                df = dfs[0]
                for additional_df in dfs[1:]:
                    df = pd.merge(df, additional_df, on='Ligand', how='outer')
                results_csv_temp = os.path.join("results", "docking_results.csv")
                df.to_csv(results_csv_temp, index=False)
                results_csv = results_csv_temp
                
    if not os.path.exists(results_csv):
        print(f"[ERROR] Docking results data source not found at: {results_csv}")
        print("Please run the screening pipeline first to generate results data.")
        return
        
    try:
        df = pd.read_csv(results_csv)
    except Exception as e:
        print(f"[ERROR] Failed to read CSV file: {e}")
        return
        
    # Determine the ligand identification column dynamically
    ligand_col = None
    for col in df.columns:
        if col.lower() in ["ligand", "compound", "ligand_name", "name"]:
            ligand_col = col
            break
            
    if not ligand_col:
        ligand_col = df.columns[0]
        print(f"[WARNING] Could not identify exact ligand column. Defaulting to: '{ligand_col}'")
        
    # Exclude non-receptor columns
    exclude_cols = {ligand_col.lower(), "smiles", "formula", "weight", "mw", "index", "unnamed: 0"}
    receptor_cols = [col for col in df.columns if col.lower() not in exclude_cols]
    
    if not receptor_cols:
        print("[ERROR] No receptor target columns identified in the docking results CSV.")
        return
        
    print(f"[INFO] Active Ligand column: '{ligand_col}'")
    print(f"[INFO] Identified target receptors: {receptor_cols}")
    
    for receptor in receptor_cols:
        print(f"\nProcessing target receptor: {receptor}")
        
        # Coerce column data to numeric to handle empty/unresolved fields
        temp_series = pd.to_numeric(df[receptor], errors='coerce')
        valid_series = temp_series.dropna()
        
        if valid_series.empty:
            print(f"  [WARNING] No valid docking scores found for receptor: {receptor}")
            continue
            
        # Find the index of the minimum value (lowest binding energy / ΔG score)
        best_idx = valid_series.idxmin()
        best_score = df.loc[best_idx, receptor]
        best_ligand = df.loc[best_idx, ligand_col]
        
        print(f"  Target Pose: {best_ligand} (Binding Energy: {best_score} kcal/mol)")
        
        # Locate receptor structure
        receptor_path = locate_receptor_pdb(receptor)
        if not receptor_path:
            print(f"  [WARNING] Could not locate protein structure for receptor '{receptor}' on disk. Skipping.")
            continue
            
        # Locate docked ligand pose
        ligand_path = locate_docked_ligand(receptor, best_ligand)
        if not ligand_path:
            print(f"  [WARNING] Could not locate docked pose file for ligand '{best_ligand}' on receptor '{receptor}'. Skipping.")
            continue
            
        print(f"  Resolved Receptor File: {receptor_path}")
        print(f"  Resolved Ligand File:   {ligand_path}")
        
        # Construct relative paths for the .cxc script relative to scenes/ folder
        cxc_receptor_path = os.path.join("..", receptor_path).replace("\\", "/")
        cxc_ligand_path = os.path.join("..", ligand_path).replace("\\", "/")
        
        cxc_filename = os.path.join(output_dir, f"{receptor}_best_pose.cxc")
        
        # Write automated UCSF ChimeraX command script
        try:
            with open(cxc_filename, "w") as f:
                # 1. Clear any old glitchy sessions
                f.write("close session\n")
                
                # 2. Open the protonated protein (#1) and docked ligand (#2)
                f.write(f"open {cxc_receptor_path}\n")
                f.write(f"open {cxc_ligand_path}\n")
                
                # 3. Clean up base visuals
                f.write("set bgColor white\n")
                f.write("hide atoms\n")
                f.write("cartoon #1\n")
                
                # 4. Target ONLY the ligand in model 2 (ignoring the flex residues)
                f.write("show #2 & ~protein atoms\n")
                f.write("style #2 & ~protein stick\n")
                f.write("color byhetero #2 & ~protein\n")
                
                # 5. Correct ChimeraX syntax to reveal only the true binding pocket
                f.write("show #1 & (#2 & ~protein) :< 5\n")
                f.write("style #1 & displayed stick\n")
                
                # 6. Calculate H-bonds strictly between the protein and the filtered ligand
                f.write("hbonds #1 restrict (#2 & ~protein) reveal true showDist false radius 0.05 dashes 6\n")
                
                # 7. Final presentation view
                f.write("lighting soft\n")
                f.write("view #2 & ~protein\n")
                
            print(f"  [SUCCESS] Generated clean ChimeraX script: {cxc_filename}")
        except Exception as e:
            print(f"  [ERROR] Failed to write scene file {cxc_filename}: {e}")

if __name__ == "__main__":
    main()